### ISSUE TITLE
[BUG] No doc_polygon found..

### ISSUE THREAD

**Issue by HERIUN** [DocsaidLab/DocAligner#1]
Appreciate your works!!

How can i handle ```result.doc_polygon=None```
```python
model = DocAligner()
result = model(img)
```

**Comment by zephyr-sh** [comment]
You can use the `Document` object's attribute `has_doc_polygon`, like this:

```python
model = DocAligner()
result = model(img)

if result.has_doc_polygon:
    # do something...
```

Alternatively, you can directly use if-else:

```python
if result.doc_polygon is not None:
    # do something...
```

**Comment by HERIUN** [comment]
Sorry for confusing.. I mean my image has document region,, but model can't find document...

**Comment by zephyr-sh** [comment]
This is not an easy question to answer. I have updated a section of the documentation, as following url:

- [**Why the Model Fail?**](https://docsaid.org/en/docs/docaligner/quickstart#why-the-model-fail)

Please take a look at the new section description to see if it can address your concerns.

**Comment by HERIUN** [comment]
Thanks for your kind explanation..

Is there any plan to release fine tuning code?

**Comment by zephyr-sh** [comment]
Thank you for inquiring, but the training module has been fully acquired, so I am unable to make it available.

If needed, I suggest referring to the following resources:

- **Training Environment Setup**: You can refer to the [**DocClassifier**](https://github.com/DocsaidLab/DocClassifier) project, which provides a complete training module. All my training modules follow the same process.
- **Backbone**: This can be accessed directly through `timm`.
- **Neck**: This is included in the `docsaidkit` project.
- **Head**: This is the only part that needs to be implemented independently, but the architecture design is documented in the technical documentation.
- **Dataset**: Public datasets are used, and they are also mentioned in the technical documentation.
